-- Content: Questions 1-30 for Domain 2.0 Infrastructure
DO $$
DECLARE
    cert_id UUID;
    obj_id UUID;
    q_id UUID;
BEGIN
    -- Look up the certification ID
    SELECT id INTO cert_id FROM certifications WHERE title = 'CompTIA Tech+ (FC0-U71)' LIMIT 1;
    
    -- Look up the objective ID for Domain 2.0
    SELECT id INTO obj_id FROM objectives WHERE certification_id = cert_id AND title = '2.0 Infrastructure' LIMIT 1;

    -- If identifiers are not found, raise an exception
    IF cert_id IS NULL OR obj_id IS NULL THEN
        RAISE EXCEPTION 'Certification or Objective not found. Ensure 2.0 Infrastructure exists.';
    END IF;

    -- Question 1: Input/Output Device Interfaces
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which interface is most commonly used today to connect external peripherals like mice, keyboards, and printers?', 'USB (Universal Serial Bus) is the standard interface for connecting a wide variety of peripherals.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'PS/2', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Parallel Port', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'USB', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Serial Port', false);

    -- Question 2: Computing Devices - Laptops
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which feature primarily distinguishes a laptop from a desktop computer?', 'Portability is the key differentiator, enabled by the integrated battery and form factor.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Processing power', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Portability', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Operating System', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Internet connectivity', false);

    -- Question 3: Internal Computing Components
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which component is responsible for cooling the CPU?', 'The Heat Sink and Fan assembly (or liquid cooler) dissipates heat generated by the CPU.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'PSU', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Heatsink/Fan', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Hard Drive', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'NIC', false);

    -- Question 4: Internet Service Types
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which type of internet connection uses fiber-optic cables to provide very high speeds?', 'Fiber-optic internet uses light signals to transmit data at high speeds.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'DSL', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Dial-up', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Fiber', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Satellite', false);

    -- Question 5: Storage
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which storage device has no moving parts and is faster than a traditional HDD?', 'An SSD (Solid State Drive) uses flash memory and has no moving mechanical parts.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Optical Drive', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'HDD', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Tape Drive', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'SSD', true);

    -- Question 6: Networking Concepts
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'What does DHCP stand for in networking?', 'DHCP stands for Dynamic Host Configuration Protocol, used to assign IP addresses automatically.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Dynamic Host Configuration Protocol', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Domain Host Control Protocol', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Data Host Connection Protocol', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Digital House Control Point', false);

    -- Question 7: Wireless Networking
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which standard is commonly referred to as Wi-Fi?', 'IEEE 802.11 is the set of standards for Wireless Local Area Networks (WLANs), branded as Wi-Fi.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '802.3', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '802.11', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '802.15', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '802.1X', false);

    -- Question 8: IoT Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'A simplified computer built into a product like a refrigerator or thermostat is best described as:', 'IoT (Internet of Things) devices or Embedded systems are specialized computers integrated into other devices.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Mainframe', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'IoT / Embedded System', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Workstation', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Server', false);

    -- Question 9: Ports and Protocols
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which port is the default for secure web browsing (HTTPS)?', 'HTTPS (HyperText Transfer Protocol Secure) uses port 443.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '80', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '21', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '443', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '25', false);

    -- Question 10: Computing Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which device is best suited for reading e-books due to its E-Ink screen?', 'E-readers are specifically designed with E-Ink screens for reading.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Tablet', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'E-reader', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Smartphone', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Smartwatch', false);

    -- Question 11: Network Hardware
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which device is required to connect a home network to an enhanced ISP signal like DSL or Cable?', 'A Modem (Modulator-Demodulator) connects the local network to the ISP''s infrastructure.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Switch', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Router', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Modem', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Access Point', false);

    -- Question 12: Peripheral Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which type of printer uses toner cartridges?', 'Laser printers use toner (powder), whereas Inkjet printers use liquid ink.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Inkjet', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Thermal', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Laser', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Impact', false);

    -- Question 13: Networking Concepts - IP
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'An IPv4 address consists of how many bits?', 'IPv4 addresses are 32-bit (e.g., 192.168.1.1). IPv6 is 128-bit.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '32', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '64', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '128', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '16', false);

    -- Question 14: Internal Components
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which component provides the physical interface for Ethernet connections?', 'The NIC (Network Interface Card) typically provides the RJ-45 Ethernet port.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'CPU', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'GPU', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'NIC', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'HDD', false);

    -- Question 15: Storage
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which type of memory is used for the BIOS/UEFI firmware?', 'BIOS/UEFI is stored on non-volatile memory like Flash ROM or EEPROM.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'SRAM', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'ROM / Flash', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'DRAM', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Virtual Memory', false);

    -- Question 16: Wireless Networking
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which technology allows for short-range wireless data exchange between devices like phones and headphones?', 'Bluetooth is designed for short-range PAN (Personal Area Network) connections.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'NFC', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Wi-Fi', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Bluetooth', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'LTE', false);

    -- Question 17: Computing Devices - Mobile
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'What is a common feature of a tablet computer?', 'Tablets rely on a touchscreen for input and display, lacking a physical keyboard.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Physical keyboard', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Touchscreen interface', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Mouse input', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Ethernet port', false);

    -- Question 18: File Systems
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which file system is native to modern Windows operating systems?', 'NTFS (New Technology File System) is the default file system for modern Windows.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'HFS+', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'NTFS', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'ext4', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'APFS', false);

    -- Question 19: Networking Concepts
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which term describes a private network that is accessible only to an organization''s staff?', 'An Intranet is a private network restricted to an organization.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Internet', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Extranet', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Intranet', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Darknet', false);

    -- Question 20: Peripheral Interfaces
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which interface transmits video only (analog)?', 'VGA (Video Graphics Array) is an older standard that carries analog video signals only.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'HDMI', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'DisplayPort', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'VGA', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Thunderbolt', false);

    -- Question 21: Networking - DNS
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'What is the function of a DNS server?', 'DNS (Domain Name System) translates human-readable domain names (like www.google.com) into IP addresses.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Assign IP addresses', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Encrypt web traffic', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Translate domain names to IP addresses', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Route packets', false);

    -- Question 22: Internal Components
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'What is the "Brain" of the computer that executes instructions?', 'The CPU (Central Processing Unit) attempts to execute the instructions of computer programs.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'HDD', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'RAM', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'CPU', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'PSU', false);

    -- Question 23: Internet Service Types
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which internet connection type uses existing telephone lines?', 'DSL (Digital Subscriber Line) transmits data over traditional copper telephone lines.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Cable', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Fiber', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'DSL', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Satellite', false);

    -- Question 24: IoT
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which is a security concern particularly associated with IoT devices?', 'IoT devices often lack robust security features, have default passwords, and do not receive updates, making them vulnerable.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'They use too much power', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Lack of robust security/updates', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'They are too expensive', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'They are incompatible with Wi-Fi', false);

    -- Question 25: Networking Hardware
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which device wireless clients connect to in order to access the wired network?', 'A WAP (Wireless Access Point) allows wireless devices to connect to a wired network.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Modem', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Wireless Access Point (WAP)', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Switch', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Patch Panel', false);

    -- Question 26: Storage Units
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which is larger: 1 TB or 100 GB?', '1 TB is approximately 1000 GB, so 1 TB is much larger than 100 GB.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '1 TB', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '100 GB', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'They are the same', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Depends on the file system', false);

    -- Question 27: Computing Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'A powerful computer used to provide services to other computers on a network is called a:', 'A Server is dedicated to providing services (files, print, web) to clients.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Client', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Laptop', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Server', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Tablet', false);

    -- Question 28: Wireless
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which cellular generation introduced significant improvements for real-time video and faster data speeds, paving way for apps?', '4G/LTE brought speeds that made real-time video streaming and modern app usage practical.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '2G', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '3G', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '4G/LTE', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '1G', false);

    -- Question 29: Peripherals
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'A webcam is considered which type of device?', 'A webcam captures video input.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Input', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Output', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Storage', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Processing', false);

    -- Question 30: Network Cables
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which cable type isolates signals using light rather than electricity, making it immune to EMI?', 'Fiber-optic cables use light, so they are not affected by Electromagnetic Interference (EMI).')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Coaxial', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Twisted Pair', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Fiber-optic', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Ethernet', false);

    -- Question 31: Wireless Standards
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'What is a primary advantage of 5GHz Wi-Fi over 2.4GHz Wi-Fi?', '5GHz offers higher data rates and has less interference (more non-overlapping channels) but has shorter range.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Better range', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Less interference / Higher Speed', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Better wall penetration', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Lower power consumption', false);

    -- Question 32: Computing Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which device is typically an "all-in-one" with screen and computer components in a single unit?', 'An All-in-One (AIO) desktop integrates the system components behind the monitor.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Tower PC', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'All-in-One', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Laptop', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Server', false);

    -- Question 33: Peripheral Connectors
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which connector is reversible and supports data, power, and video?', 'USB-C is a reversible connector that can carry data, high power, and video signals.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'USB-A', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Micro-USB', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'USB-C', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'HDMI', false);

    -- Question 34: Storage
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which storage type is volatile?', 'RAM (Random Access Memory) is volatile; it loses data when power is off.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'SSD', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'RAM', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'HDD', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Flash Drive', false);

    -- Question 35: Networking Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which device connects different networks together and directs traffic between them?', 'A Router connects distinct networks (like LAN to WAN) and routes traffic based on IP addresses.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Hub', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Switch', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Router', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Bridge', false);

    -- Question 36: Internal Components
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which component converts AC power to DC power for the computer?', 'The Power Supply Unit (PSU) performs AC to DC conversion.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'UPS', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'VRM', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Inverter', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'PSU', true);

    -- Question 37: Cloud Concepts
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Using a cloud service to store files (like Google Drive or Dropbox) is an example of:', 'File storage services typically fall under SaaS (Software as a Service) from a user perspective, or Cloud Storage concepts.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'SaaS', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'IaaS', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'PaaS', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Virtualization', false);

    -- Question 38: Cellular Data
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which technology allows a smartphone to act as a wireless router for other devices?', 'Hotspot (or Tethering) functionality shares the cellular connection via Wi-Fi.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Roaming', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Hotspot', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Airplane Mode', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'NFC', false);

    -- Question 39: Interfaces
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which connection is faster for an external hard drive: USB 2.0 or USB 3.0?', 'USB 3.0 (and newer) is significantly faster than USB 2.0.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'USB 2.0', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'USB 3.0', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'They are the same', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Depends on the cable length', false);

    -- Question 40: Networking
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'What is the standard connector type for a wired Ethernet connection?', 'RJ-45 is the standard 8-pin connector for Ethernet cables.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'RJ-11', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'RJ-45', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'USB', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'HDMI', false);

    -- Question 41: Storage Media
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which optical media typically holds the most data?', 'Blu-ray discs hold significantly more data (25GB+) than DVDs (4.7GB) or CDs (700MB).')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'CD', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'DVD', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Blu-ray', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Floppy Disk', false);

    -- Question 42: Computing Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which form factor is designed to be mounted in a rack in a data center?', 'Rack-mounted servers are flat, wide computers designed to fit into standard server racks.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Tower', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Rack-mount', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Mini-PC', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Laptop', false);

    -- Question 43: Wireless Security
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which encryption standard is currently recommended for securing home Wi-Fi networks?', 'WPA2 (or WPA3) is the standard. WEP is obsolete and insecure. WPA is also outdated.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'WEP', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'WPA', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'WPA2/WPA3', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Open', false);

    -- Question 44: Printers
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'What is a common use for a 3D printer?', '3D printing (additive manufacturing) creates physical objects from digital models.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Printing receipts', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Creating plastic prototypes/parts', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'High volume document printing', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Photo printing', false);

    -- Question 45: Internal Components
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'What does GPU stand for?', 'GPU stands for Graphics Processing Unit.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'General Processing Unit', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Graphics Processing Unit', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Global Power Unit', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Graphical Performance Unit', false);

    -- Question 46: Networking
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'A network that covers a large geographical area (like a city or country) is a:', 'WAN (Wide Area Network) covers large distances. LAN is local.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'LAN', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'PAN', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'WAN', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'WLAN', false);

    -- Question 47: IoT
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Smart home devices (lights, locks) often use which low-power wireless protocols?', 'Zigbee and Z-Wave are common low-power protocols for home automation.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'LTE', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Zigbee/Z-Wave', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Satellite', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'NFC', false);

    -- Question 48: Connectivity
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which physical connection is known for "Daisy Chaining" devices?', 'Thunderbolt (and older FireWire) supports daisy chaining multiple devices in a sequence.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'VGA', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Ethernet', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Thunderbolt', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'HDMI', false);

    -- Question 49: Storage
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'When a computer runs out of RAM, it uses a portion of the hard drive as:', 'Virtual Memory (or Swap/Page file) is used when physical RAM is full.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Cache', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Virtual Memory', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'System Reserve', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Buffer', false);

    -- Question 50: Computing Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'A Gaming Console (e.g., Xbox, PlayStation) is what type of device?', 'It is a specialized computing device designed primarily for gaming and media.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'General Purpose PC', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Specialized Device', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'IoT Device', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Mainframe', false);

    -- Question 51: Interfaces
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which port is typically blue and has 15 holes arranged in 3 rows?', 'This describes the VGA connector.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'DVI', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'VGA', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Serial', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Parallel', false);

    -- Question 52: Networking
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Using a VPN connects you securely to a private network over the:', 'Public Internet. VPN creates a secure tunnel through the public internet.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Local LAN', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Public Internet', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Bluetooth connection', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'NFC connection', false);

    -- Question 53: Internet Service
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which internet service is best for rural areas where cables cannot be run?', 'Satellite internet is the primary option for remote/rural locations without wired infrastructure.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Fiber', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'DSL', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Satellite', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Cable', false);

    -- Question 54: Memory
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Does adding more RAM typically increase computer performance?', 'Yes, more RAM allows more programs to run simultaneously without paging to the slower hard drive.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Yes', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'No', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Only if you have an SSD', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'It slows it down', false);

    -- Question 55: Peripherals
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which device allows a computer to scan physical documents into digital files?', 'A Scanner (or Multifunction Printer) digitizes physical documents.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Printer', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Scanner', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Monitor', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Projector', false);

    -- Question 56: Infrastructure
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'What is the "cloud"?', 'The Cloud refers to servers accessed over the internet, and the software/databases running on those servers.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'The internet itself', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Servers accessed over the internet', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Wireless networks', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Satellite satellites', false);

    -- Question 57: Networking
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which wireless standard sends data using light waves (like a remote control)?', 'IR (Infrared) uses light waves. It requires line-of-sight.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Bluetooth', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Wi-Fi', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Infrared (IR)', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'NFC', false);

    -- Question 58: Computing Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which component represents the "long term memory" of a computer?', 'The Hard Drive (or SSD) stores data permanently, unlike RAM which is short-term/working memory.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'CPU', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'RAM', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Hard Drive', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Cache', false);

    -- Question 59: IoT
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'What allows a smart thermostat to be controlled remotely?', 'Internet connectivity (Wi-Fi) allows remote control via an app.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Bluetooth', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'A strong battery', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Internet Connectivity', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'NFC', false);

    -- Question 60: Networking
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which device is a "multi-port repeater" that broadcasts data to ALL ports (considered obsolete)?', 'A Hub broadcasts data to all ports, causing collisions. Switches are intelligent.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Switch', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Router', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Hub', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Modem', false);

    -- Question 61: Peripherals
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which input device is commonly used for graphic design to draw directly on a surface?', 'A Digitizer (or Graphics Tablet) allows for precise drawing input.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Mouse', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Digitizer / Drawing Tablet', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Trackball', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Scanner', false);

    -- Question 62: Internal Components
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'A sound card typically connects to the motherboard via which slot?', 'Modern expansion cards, including sound cards, use PCIe (Peripheral Component Interconnect Express) slots.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'AGP', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'PCIe', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'IDE', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'DIMM', false);

    -- Question 63: Network Types
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Bluetooth headphones connecting to a smartphone creates which type of network?', 'A PAN (Personal Area Network) is for very short-range connections around a person.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'LAN', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'WAN', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'PAN', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'MAN', false);

    -- Question 64: Storage
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which technology allows multiple hard drives to work together for redundancy or speed?', 'RAID (Redundant Array of Independent Disks) adds redundancy or performance.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'TRIM', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'RAID', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'SATA', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'NVMe', false);

    -- Question 65: Computing Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'A drone is an example of which type of system?', 'Drones are Autonomous Vehicles / IoT devices depending on context, but "IoT" or "Autonomous" fits broadly.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Desktop', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Workstation', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'IoT / Autonomous Vehicle', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Mainframe', false);

    -- Question 66: Internet
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Bandwidth is best described as:', 'Bandwidth is the maximum data transfer rate of a network or internet connection.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'The speed of the CPU', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'The maximum data transfer rate', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'The amount of storage space', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'The latency of the connection', false);

    -- Question 67: Ports
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which port number is associated with unsecure HTTP web traffic?', 'HTTP uses port 80.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '21', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '80', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '443', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '3389', false);

    -- Question 68: Monitors
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which monitor technology is known for deep blacks and high contrast because each pixel provides its own light?', 'OLED (Organic Light-Emitting Diode) pixels are self-emissive, allowing perfect blacks.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'LCD', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'TN', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'OLED', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'CRT', false);

    -- Question 69: Networking
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which device acts as a security guard for a network, allowing or denying traffic?', 'A Firewall filters traffic based on security rules.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Switch', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Modem', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Firewall', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Repeater', false);

    -- Question 70: Interfaces
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'What is "Plug and Play"?', 'It refers to the operating system automatically detecting and configuring new hardware devices.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Devices that require manual driver installation', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Automatic detection and configuration of hardware', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'A type of game controller', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Power saving mode', false);

    -- Question 71: Wireless
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which generation of cellular technology introduced 5G?', '5G is the 5th generation, succeeding 4G/LTE.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '3G', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '4G', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '5G', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '6G', false);

    -- Question 72: Internal Components
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which of the following is an example of an expansion card?', 'A Video Card (GPU) is a common expansion card plugged into the motherboard.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'CPU', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'RAM Stick', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Video Card', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'USB Cable', false);

    -- Question 73: Storage
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which file system is compatible with both MacOS and Windows out of the box (for read/write)?', 'ExFAT is designed for flash drives and is compatible with both Windows and MacOS.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'NTFS', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'APFS', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'ExFAT', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'HFS', false);

    -- Question 74: Networking
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Latency is best defined as:', 'Latency is the delay in data transmission (ping time).')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Total data transfer', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'The delay between sending and receiving data', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'The physical length of the cable', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'The cost of the internet', false);

    -- Question 75: Computing Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which device is a high-performance computer designed for specialized technical tasks like CAD or video editing?', 'A Workstation is a high-performance PC for professional tasks.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Netbook', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Workstation', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Thin Client', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Server', false);

    -- Question 76: IoT
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which technology enables IoT devices to communicate over very long distances with low power consumption?', 'LoRaWAN (Long Range Wide Area Network) is designed for long-range, low-power IoT.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Wi-Fi', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Bluetooth', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'LoRaWAN', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'NFC', false);

    -- Question 77: Cables
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which cable is used to connect a telephone to a wall jack?', 'RJ-11 is the standard telephone connector.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'RJ-45', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'RJ-11', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'USB-C', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Coaxial', false);

    -- Question 78: Internal Components
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'System memory that retains data only while the computer is powered on is:', 'RAM (Random Access Memory) requires power to maintain data.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'ROM', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'BIOS', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'RAM', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'CMOS', false);

    -- Question 79: Cloud
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which cloud model provides a platform for developers to build and deploy applications without managing infrastructure?', 'PaaS (Platform as a Service) provides the development framework.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'SaaS', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'PaaS', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'IaaS', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'DbaaS', false);

    -- Question 80: Networking
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which device is a simple "pass-through" connecting a computer''s Wi-Fi card to the network antenna?', 'This is just the Antenna itself, but typically the question refers to the WAP or Adapter. In this context, "Antenna" sends signals.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Router', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Switch', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Antenna', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Modem', false);

    -- Question 81: Interfaces
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'DisplayPort is primarily a competitor to which other digital interface?', 'DisplayPort competes directly with HDMI for video/audio connection.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'VGA', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'HDMI', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'PS/2', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'USB-A', false);

    -- Question 82: Storage
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'What is the main benefit of an NVMe SSD over a SATA SSD?', 'NVMe connects via PCIe and offers significantly higher speeds (bandwidth) than the older SATA interface.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Cheaper cost', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'More storage capacity', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Much faster data transfer speeds', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Physical durability', false);

    -- Question 83: Computing Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which device is an eBook reader most likely to use for connectivity?', 'Most e-Readers use Wi-Fi to download books.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Ethernet', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Wi-Fi', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Fiber', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Satellite', false);

    -- Question 84: Wireless
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'NFC (Near Field Communication) is most commonly used for:', 'Contactless payments (like mobile pay) are the primary consumer use case for NFC.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Long distance communication', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Connect keyboards', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Contactless payments', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Streaming video', false);

    -- Question 85: Internal Components
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which BIOS/UEFI setting might you change to boot from a URL over the network?', 'PXE (Preboot Execution Environment) allows booting from a network server.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Secure Boot', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'PXE Boot (Network Boot)', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Overclocking', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'XMP', false);

    -- Question 86: Networking
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which network topology connects every device to a central switch?', 'Star topology connects all nodes to a central device.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Bus', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Ring', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Star', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Mesh', false);

    -- Question 87: IoT
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which is an example of a "Wearable" IoT device?', 'A Activity Tracker (like Fitbit) is worn on the body.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Smart Refrigerator', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Smart Bulb', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Activity Tracker', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Smart TV', false);

    -- Question 88: Ports
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which port is used for sending email via SMTP?', 'SMTP (Simple Mail Transfer Protocol) typically uses port 25 (or 587/465).')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '25', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '80', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '110', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, '143', false);

    -- Question 89: Cloud
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which cloud characteristic allows resources to automatically scale up or down based on demand?', 'Rapid Elasticity (or Scalability) allows dynamic resource adjustment.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'broad network access', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Rapid elasticity', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Measured service', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'On-demand self-service', false);

    -- Question 90: Hardware
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'What does the term "form factor" refer to in computing?', 'Form Factor refers to the physical size, shape, and layout specifications of hardware (e.g., ATX, Micro-ATX motherboard).')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'The speed of the processor', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'The operating system version', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'The physical size and shape specifications', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'The software license specificstions', false);

    -- Question 91: Networking
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'A MAC address is a unique identifier assigned to:', 'A Netowrk Interface Controller (NIC) has a burned-in MAC address.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Software applications', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'A Network Interface Card (NIC)', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Hard Drives', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'User accounts', false);

    -- Question 92: Computing Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which device is primarily designed for consuming media like books, movies, and web browsing, with a touch interface?', 'Tablets are optimized for media consumption.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Server', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Tablet', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Desktop', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Switch', false);

    -- Question 93: Storage
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which concept refers to saving data to a remote server for disaster recovery?', 'Cloud Backup involves sending a copy of data to an off-site cloud server.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Local Backup', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Cloud Backup', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Partitioning', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Formatting', false);

    -- Question 94: Internal Components
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which component has the highest direct impact on the number of browser tabs you can keep open efficiently?', 'RAM (Memory) stores the active data for running programs. More tabs require more RAM.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Hard Drive space', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'GPU speed', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'RAM', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Power Supply wattage', false);

    -- Question 95: Wireless
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which symbol usually indicates a Wi-Fi connection is available?', 'The fan-shaped or curved signal bars icon represents Wi-Fi.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Bluetooth B', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Fan-shaped / Curved bars', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Globe', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Airplane', false);

    -- Question 96: IoT
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'A "Smart Speaker" (like Echo or HomePod) primarily uses which input method?', 'Voice commands are the primary input method for smart speakers.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Keyboard', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Voice Control', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Touchscreen', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Mouse', false);

    -- Question 97: Interfaces
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which cable is used to transmit high-quality digital audio and video from a computer to a monitor or TV?', 'HDMI is the standard for high-quality digital A/V.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'VGA', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'HDMI', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'DVI-A', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Aux', false);

    -- Question 98: Networking
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which protocol is used to retrieve emails from a server?', 'IMAP (and POP3) retrieves mail. SMTP sends mail.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'SMTP', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'IMAP', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'FTP', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'HTTP', false);

    -- Question 99: Computing Devices
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which device is traditionally a large, powerful computer used for processing vast amounts of data (like census data)?', 'Mainframes are designed for high-volume data processing and reliability.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Microcomputer', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Mainframe', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Workstation', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Laptop', false);

    -- Question 100: Internal Components
    INSERT INTO questions (objective_id, type, points, text, explanation)
    VALUES (obj_id, 'multiple_choice', 10, 'Which component is the main printed circuit board found in general-purpose computers?', 'The Motherboard is the main circuit board.')
    RETURNING id INTO q_id;
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Daughterboard', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Motherboard', true);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Backplane', false);
    INSERT INTO answers (question_id, text, is_correct) VALUES (q_id, 'Breadboard', false);

END $$;
